### ISSUE TITLE
Compile - trackedVersionsLists0.bz2 - invalid data stream

### ISSUE THREAD

**Issue by Barrocas** [gobolinux/Scripts#10]
Running Gobo 016,

Whenever doing a 'Compile' of any program, either as 'super-user' or 'root', the following error message is always listed:

GetAvailable: Cannot open /Data/Variable/tmp/Scripts-hugo/cache/trackedVersionsLists0.bz2 - invalid data stream
GetAvailable: Removing...
GetAvailable: Cannot open /Data/Variable/tmp/Scripts-hugo/cache/trackedVersionsLists0.bz2 - invalid data stream
GetAvailable: Removing...

**Comment by hishamhm** [comment]
This is a harmless error message. This file is no longer used, so it was
removed from the server as part of a major cleanup.

To stop seeing the message, edit /System/Settings/Scripts/GetAvailable.conf
and remove the trackedVersions URL (make that variable an empty list: [] )

@lucasvr: This configuration needs to be updated in the Scripts repo as
well, but I can't make the change right now.
