### ISSUE TITLE
CheckDependencies doesn't know about Aliens

### ISSUE THREAD

**Issue by lucasvr** [gobolinux/Scripts#13]
```shell
CheckDependencies: PIP:PyOpenGL is not installed.
CheckDependencies: Compile recipe for PIP:PyOpenGL  or skip this dependency? [C]Compile/[S]Skip/[CA]Compile All/[SA]Skip All
```
Two things to note:
1. CheckDependencies should, ideally, query the Aliens database to learn about which dependencies managed by Aliens are available
2. The second message should be changed to something along the lines of "Install dependency $DEP or skip it? [I]Install / [S]Skip / [IA] Install All / [SA] Skip All"

**Comment by hishamhm** [comment]
was this using Compile or InstallPackage?

**Comment by lucasvr** [comment]
That was using Compile. I haven't tried with InstallPackage. Either case, the piece of code to be improved seems to be the GetAvailable Python script.
