### ISSUE TITLE
porting

### ISSUE THREAD

**Issue by mgood7123** [gobolinux/Scripts#19]
would it be possible to port this to another os? if so what would u reccomend in terms of testing if this works as to not mess up the os itself should something go wrong

**Comment by mwh** [comment]
This is a bug tracker, not a forum.

There is nothing to stop anybody making whatever hierarchy they want, but another system would have its own package manager already and little use for most of Scripts.

**Comment by mgood7123** [comment]
if possible could u point me to a location that would have an in-depth documentation of exactly how ur fhs works, like what happens during instalation and removing of a package
