### ISSUE TITLE
mktemp program

### ISSUE THREAD

**Issue by AitorATuin** [gobolinux/Scripts#2]
The (really old) recipe for Scripts was depending on MkTemp (https://www.mktemp.org/mktemp.html); according to the project webpage that program is compatible with GNU's one. is there a good reason to use the version provided by MkTemp? can we just remove that dependency since seems that is not adding anything but another dep?

**Comment by lucasvr** [comment]
That seems to be a left-over from ages ago. Feel free to go ahead and remove it. Thanks!

**Comment by AitorATuin** [comment]
Ok, I will remove it from the Scripts recipe
