### ISSUE TITLE
GetAvailable and FindPackage trying to run on Python 3

### ISSUE THREAD

**Issue by cleberzavadniak** [gobolinux/Scripts#28]
**GoboLinux 016.01**

While trying to `sudo InstallPackage Scripts`, I had to change the magic line of both scripts to `/bin/env python2.7`.

Maybe this problem affects other scripts as well.

What would be the best approach? Change magic lines or `2to3` all scripts?

**Comment by Nuc1eoN** [comment]
By now we are on GoboLinux 017. I have never encountered this issue, but also Scripts currently is supposed to be updated like so:
```sh
cd /Programs/Scripts/Current
git pull && UpdateSettings --auto Scripts && make
```
which works well.
Therefore closing.
