### ISSUE TITLE
GuessLatest with "inconsistent use of tabs and spaces in indentation"

### ISSUE THREAD

**Issue by cleberzavadniak** [gobolinux/Scripts#29]
**GoboLinux 016.01**
Line: 142 (`sys.exit(1)`)

It doesn't seems to be the case in this repository, but on my install of GoboLinux 016, at the same "side quest" that generated #28 , this script contained this bizarre error.

Simply fixed it (it's **so** weird to `:set noexpandtabs`...), but no idea what made this happen...

**Comment by Nuc1eoN** [comment]
Same as the other bug report. We are on goboLinux 017 and this probably cannot be reproduced anymore. But if it still happens feel free to reopen.
