### ISSUE TITLE
Compile Scripts - delete settings

### ISSUE THREAD

**Issue by Barrocas** [gobolinux/Scripts#8]
In a computer with Gobo 015 (Enlightenment), run 'Compile LibXFCE4UI 4.12.0' (a part of Xfce4, never previously installed).

It compiles, and at the end, it backs up the settings and asks the user to 'del: Settings/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml'

I found this strange, since there should be no previous settings, as it was never installed.

If the user accepts to delete, the settings will be stored in the programs /Resources/SettingsBackup , and that is ok, since it should write the new settings in the respective folders,  but it doesn't, the new program's /Settings will be empty.

When it Symlinks to finalize installation, there are no files in the /Settings folder to link to, just empty folders. That will end up with an incomplete installation.

I ended up having to restore all settings manually and SymlinkProgram again.

**Comment by Barrocas** [comment]
The same happens in other programs for Xfce, like EXO, or Garcon, and it has the same result.

The options should be to:
1 - keep the previous settings, not updating.
2 - update/replace by the new ones.
3 - allow to compare/edit (for advanced users)

Asking the user to delete the settings (and not apply the new ones), is not a good option.

**Comment by lucasvr** [comment]
Fixed by https://github.com/gobolinux/Compile/commit/88d99e09134abb3e0c33a0daf73779e9fd1541a8
